# Generated by Django 3.1.3 on 2020-11-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
