# Generated by Django 3.1.3 on 2020-11-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20201125_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
