# Generated by Django 3.1.3 on 2020-11-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
