# Generated by Django 3.1.3 on 2020-12-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0009_auto_20201204_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
    ]
