# Generated by Django 3.0.8 on 2020-10-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('oriprice', models.IntegerField()),
                ('curprice', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('img1', models.ImageField(upload_to='mobiles')),
                ('img2', models.ImageField(upload_to='mobiles')),
                ('img3', models.ImageField(upload_to='mobiles')),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('processor', models.CharField(max_length=20)),
                ('pricamera', models.FloatField()),
                ('seccamera', models.FloatField()),
                ('ram', models.IntegerField()),
                ('internal', models.IntegerField()),
                ('color', models.CharField(max_length=15)),
                ('battery', models.IntegerField()),
            ],
        ),
    ]
