# Generated by Django 3.0.8 on 2020-11-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
