# Generated by Django 3.0.8 on 2020-11-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201101_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
