# Generated by Django 3.0.8 on 2020-11-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201103_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory1', models.CharField(max_length=25)),
                ('accbrand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('oriprice', models.IntegerField()),
                ('curprice', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('img1', models.ImageField(upload_to='accessories')),
                ('img2', models.ImageField(upload_to='accessories')),
                ('img3', models.ImageField(upload_to='accessories')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('acctype', models.CharField(max_length=40, null=True)),
                ('accfeatures', models.CharField(max_length=40, null=True)),
                ('accinterfaces', models.CharField(max_length=40, null=True)),
                ('acccapacity', models.IntegerField(null=True)),
                ('accconnectivity', models.CharField(max_length=40, null=True)),
                ('discount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory2', models.CharField(max_length=25)),
                ('appbrand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('oriprice', models.IntegerField()),
                ('curprice', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('img1', models.ImageField(upload_to='appliances')),
                ('img2', models.ImageField(upload_to='appliances')),
                ('img3', models.ImageField(upload_to='appliances')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('apptype', models.CharField(max_length=40)),
                ('appcapacity', models.IntegerField()),
                ('appsize', models.IntegerField(null=True)),
                ('appfeatures', models.CharField(max_length=40, null=True)),
                ('discount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('oriprice', models.IntegerField()),
                ('curprice', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('img1', models.ImageField(upload_to='pc')),
                ('img2', models.ImageField(upload_to='pc')),
                ('img3', models.ImageField(upload_to='pc')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('pcram', models.IntegerField()),
                ('pcharddisk', models.IntegerField()),
                ('pcprocessor', models.CharField(max_length=20)),
                ('pcssd', models.IntegerField()),
                ('discount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('oriprice', models.IntegerField()),
                ('curprice', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('img1', models.ImageField(upload_to='tv')),
                ('img2', models.ImageField(upload_to='tv')),
                ('img3', models.ImageField(upload_to='tv')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('screensize', models.IntegerField()),
                ('resolution', models.CharField(max_length=20)),
                ('screentype', models.CharField(max_length=10)),
                ('smarttv', models.CharField(max_length=10)),
                ('discount', models.IntegerField(null=True)),
            ],
        ),
    ]
