# Generated by Django 3.0.8 on 2020-11-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_accessories_appliances_pc_tv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='appliances',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='mobiles',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='img3',
        ),
    ]
