# Generated by Django 3.1.3 on 2020-11-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201112_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='appliances',
            name='description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='pc',
            name='description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='tv',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
