# Generated by Django 3.1.3 on 2020-11-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201117_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('mailid', models.EmailField(max_length=254)),
                ('tablename', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30, null=True)),
                ('productid', models.IntegerField()),
            ],
        ),
    ]
