# Generated by Django 3.1.3 on 2020-11-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
