# Generated by Django 3.1.3 on 2020-11-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201124_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiles',
            name='curprice',
        ),
    ]
