# Generated by Django 3.1.3 on 2020-11-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_mobiles_curprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='curprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
