# Generated by Django 3.1.3 on 2020-11-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_cart_hi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='hi',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='mailid',
        ),
    ]
