# Generated by Django 3.1.3 on 2020-11-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20201125_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
