# Generated by Django 3.1.3 on 2020-11-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='category',
            field=models.CharField(choices=[('MOBILES', 'MOBILES'), ('TABLETS', 'TABLETS')], default='MOBILES', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='internal',
            field=models.IntegerField(choices=[('512', '512MB'), ('1', '1GB'), ('4', '4GB'), ('6', '6GB'), ('8', '8GB'), ('16', '16GB'), ('32', '32GB'), ('64', '64GB'), ('128', '128GB'), ('256', '256GB')], default='512'),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='ram',
            field=models.IntegerField(choices=[('512', '512MB'), ('1', '1GB'), ('2', '2GB'), ('3', '3GB'), ('4', '4GB'), ('6', '6GB'), ('8', '8GB'), ('12', '12GB'), ('16', '16GB')], default='512'),
        ),
    ]
