# Generated by Django 3.1.3 on 2020-11-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20201130_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='resolution',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('FULL HD', 'FULL HD'), ('HD READY', 'HD READY'), ('4K', '4K'), ('8K', '8K')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='tv',
            name='screentype',
            field=models.CharField(choices=[('LED', 'LED'), ('OLED', 'OLED'), ('QLED', 'QLED')], default='LED', max_length=10),
        ),
        migrations.AlterField(
            model_name='tv',
            name='smarttv',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=10),
        ),
    ]
