# Generated by Django 3.1.3 on 2020-11-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20201130_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='subcategory1',
            field=models.CharField(choices=[('HEADSETS', 'HEADSETS'), ('MOBILE CASES', 'MOBILE CASES'), ('TEMPERED GLASS', 'TEMPERED GLASS'), ('MOBILE CHARGERS', 'MOBILE CHARGERS'), ('MOUSE', 'MOUSE'), ('POWER BANKS', 'POWER BANKS'), ('EXTERNAL HARD DISKS', 'EXTERNAL HARD DISKS'), ('KEYBOARDS', 'KEYBOARDS')], default='HEADSETS', max_length=25),
        ),
        migrations.AlterField(
            model_name='appliances',
            name='subcategory2',
            field=models.CharField(choices=[('WASHING MACHINE', 'WASHING MACHINE'), ('REFRIGERATORS', 'REFRIGERATORS'), ('AIR CONDITIONERS', 'AIR CONDITIONERS'), ('FANS', 'FANS')], default='FANS', max_length=25),
        ),
    ]
